### ISSUE TITLE
save cart item(items) for auth users for few days( in db) and for guests in session 

### ISSUE THREAD

**Issue by saeed7m** [Crinsane/LaravelShoppingcart#143]
how can I save items in db when users login, and show the cart items if they login from another pc ?

**Comment by raylight75** [comment]
I have same question is it posible and how.

**Comment by lukepolo** [comment]
Just serialize the cart when it is unserialized it should be able to be
loaded back into the cart.

**Comment by raylight75** [comment]
Some short basic example

**Comment by lukepolo** [comment]
I actually dont use this package, I just listen for what's going on to improve my own cart package, since this seems to be mostly dead. 

This is natively built into mine https://github.com/lukepolo/laracart. 

Look at this piece of code to see how I did it in mine if you want to replicate it here 

https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php#L90

**Comment by raylight75** [comment]
Thanks lukepolo

**Comment by Crinsane** [comment]
@saeed7m @raylight75 @lukepolo Update was long overdue, but the current master branch holds the code for the new version where a `store()` and `restore()` method are added. If you feel like it, give it a try.
