### ISSUE TITLE
Remove regeneration of rowId on update

### ISSUE THREAD

**Issue by petraeus** [Crinsane/LaravelShoppingcart#214]
Closed

**Comment by sweet-greg** [comment]
Can you explain why this is closed? RowId's still get regenerated with version 2.2.3 when changing options.

**Comment by sweet-greg** [comment]
@Crinsane this is a pain when using this module in an API, I don't understand why this is a smart move to regenerate the ID when options are updated... Can you comment?

**Comment by Crinsane** [comment]
It's actually quite simple. The rowId is the unique identifier of an item in the cart.

Say you buy a "red t-shirt, size M", this will give you a certain rowId based on the product itself and the options (color = red, size = M)
If you add another item "blue t-shirt, size M", you're buying the exact same product, but with different options, so it will need an other rowId to be uniquely identifiable.

Now if for some reason I would choose to change the color of the second item to "red" I'm basically buying two of the same products, same options. So I don't want to rows in my cart, I want one row, with a quantity of 2.

So that's why the rowId will change when updating any options. Hope that clears it up @sweet-greg

**Comment by sweet-greg** [comment]
I understand your thinking, but you normally use a unique SKU per product for that, no? In my case options of the cart are, for example, if you would like the product the be giftwrapped or not...

**Comment by Crinsane** [comment]
Yes, there are indeed situations where you have a unique SKU for each product and options. But a lot of people don't have those.
I can understand how this could be a problem in your specific situation. But then again, if you'd only work with the SKU, how would you distinguish two of the same SKU's in a cart, where one has to be giftwrapped and one doesn't?

**Comment by sweet-greg** [comment]
you're right. I don't really need to support that kind of behaviour in my case, but this module should ;)

**Comment by sweet-greg** [comment]
@Crinsane when you update a row, and hence the rowId gets updated, how can you retrieve the new ID? Cart::update() does not return anything...

**Comment by Crinsane** [comment]
I think that should be fixed indeed. The update method should return the CartItem that was updated. So if you're willing to make a PR, feel free to do so :)
