### ISSUE TITLE
Product discounts

### ISSUE THREAD

**Issue by juanklagos** [Crinsane/LaravelShoppingcart#280]
I am creating a cart and wanted to add discounts to the products, in the array of options, I put a discount option, but when I update this option, also updates the id, and I change the position of the product in the cart, so investigate your Code, and comment where this function to update the id, my question is how bad is it to do this?

  public function updateFromArray(array $attributes)
    {
        $this->id       = array_get($attributes, 'id', $this->id);
        $this->qty      = array_get($attributes, 'qty', $this->qty);
        $this->name     = array_get($attributes, 'name', $this->name);
        $this->price    = array_get($attributes, 'price', $this->price);
        $this->priceTax = $this->price + $this->tax;
        $this->options  = new CartItemOptions(array_get($attributes, 'options', $this->options));

        //$this->rowId = $this->generateRowId($this->id, $this->options->all());
    }

The code works perfectly !! But is it bad to do so?

**Comment by Crinsane** [comment]
This has been asked before actually, so for more details look at previous issues. 
But the rowid is regenerated because it is based on all properties (name, price, options, etc) of the item. 
Because when I add one red shirt and one yellow shirt to the cart. And next I change the yellow shirt to red, I expect 1 row in the cart with two red shirts and not 2 rows each with the exact same red shirt. So I wouldn't recommend that change. But of course I'm not stopping you. 😋
